## _install pytorch_

In [2]:
conda install pytorch torchvision -c pytorch

Solving environment: done

## Package Plan ##

  environment location: /Users/song-yeojin/opt/anaconda3

  added / updated specs:
    - pytorch
    - torchvision


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ffmpeg-4.3                 |       h0a44026_0        10.1 MB  pytorch
    gettext-0.21.0             |       h7535e17_0         2.6 MB
    gnutls-3.6.15              |       hed9c0bf_0         974 KB
    lame-3.100                 |       h1de35cc_0         316 KB
    libtasn1-4.16.0            |       h9ed2024_0          53 KB
    libuv-1.40.0               |       haf1e3a3_0         334 KB
    nettle-3.7.3               |       h230ac6f_1         380 KB
    openh264-2.1.1             |       h8346a28_0         655 KB
    pytorch-1.11.0             |          py3.9_0        70.0 MB  pytorch
    torchvision-0.12.0         |         py39_cpu         7.2 MB  pytorch
    -----------

In [1]:
import torch

In [3]:
import numpy as np

In [5]:
x = torch.Tensor([[1,2],[3,4]])
x = torch.from_numpy(np.array([[1,2],[3,4]]))

In [6]:
x

tensor([[1, 2],
        [3, 4]])

In [7]:
x = np.array([[1,2],[3,4]])

In [8]:
x

array([[1, 2],
       [3, 4]])

In [11]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [12]:
print(t.dim()) #rank
print(t.shape)
print(t.size())

1
torch.Size([7])
torch.Size([7])


## _vector slicing_

In [13]:
print(t[0],t[1],t[-1]) #index
print(t[2:5],t[4:-1])
print(t[:2],t[3:])

tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [14]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [15]:
print(t.dim())
print(t.shape)

2
torch.Size([4, 3])


In [16]:
print(t[:,1]) #첫번째 차원 전체선택, 2번째 것만 가져옴
print(t[:,1].shape)

tensor([ 2.,  5.,  8., 11.])
torch.Size([4])


In [17]:
print(t[:,:-1])

tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


## _broadcasting_  
행렬간 연산을 할 때 자동으로 크기를 맞춰서 연산을 수행하게 해주는 기능

In [18]:
m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([[2,2]])
print(m1 + m2)

tensor([[5., 5.]])


In [20]:
#vector + scalar
m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([3]) #broadcasting으로 인해 3,3 vector로 인식
print(m1 + m2)

tensor([[6., 6.]])


연산 과정에서 [1,2] -> [1,2],[1,2]  
[3],[4] - > [3,3],[4,4] 로 변경

In [22]:
# 2 by 1 vector + 1 by 2 vector
m1 = torch.FloatTensor([[1,2]]) #1 by 2 vector
m2 = torch.FloatTensor([[3],[4]]) #2 by 1 vector
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


## _Matrix Multiplication_

In [24]:
m1 = torch.FloatTensor([[1,2],[3,4]])#2 by 2
m2 = torch.FloatTensor([[1],[2]])#2 by 1
print("Shape of m1 matrix:",m1.shape)
print("Shape of m2 matrix:",m2.shape)
print(m1.matmul(m2)) #2 by 1

Shape of m1 matrix: torch.Size([2, 2])
Shape of m2 matrix: torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


### _element-wise multiplication_  
동일한 크기의 행렬이 동일한 위치에 있는 원소끼리 곱하는 것

In [25]:
m1 = torch.FloatTensor([[1,2],[3,4]])
m2 = torch.FloatTensor([[3],[4]])
print("Shape of m1 matrix:",m1.shape)
print("Shape of m2 matrix:",m2.shape)
print(m1 * m2)
print(m1.mul(m2))

Shape of m1 matrix: torch.Size([2, 2])
Shape of m2 matrix: torch.Size([2, 1])
tensor([[ 3.,  6.],
        [12., 16.]])
tensor([[ 3.,  6.],
        [12., 16.]])


broadcasting 이후 곱셈 연산을 수행. [3],[4]->[3,3],[4,4]

## _mean_

In [26]:
t = torch.FloatTensor([1,2])
print(t.mean())

tensor(1.5000)


In [28]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t.mean())

tensor(2.5000)


In [29]:
#dim 사용
print(t.mean(dim=0)) #dim=0이란 첫번째 차원, 즉 첫번째 행. dim을 인자로 준다는 것은 그 행을 지운다는 것.

tensor([2., 3.])


In [30]:
print(t.mean(dim=1)) #열을 지운다

tensor([1.5000, 3.5000])


In [31]:
print(t.mean(dim=-1)) # 마지막 차원을 지운다 = 열을 지운다

tensor([1.5000, 3.5000])


## _sum_

In [33]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t.sum())

tensor(10.)


In [36]:
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


## _Max & ArgMax_  
max는 원소의 최댓값을 리턴하고, argmax는 최댓값의 인덱스를 리턴한다.

In [37]:
t = torch.FloatTensor([[1, 2], [3, 4]])

In [38]:
print(t.max())

tensor(4.)


In [39]:
print(t.max(dim=0)) #max에 dim인자를 주면 argmax도 함께 리턴됨. 

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


In [40]:
print('Max: ', t.max(dim=0)[0])
print('Argmax: ', t.max(dim=0)[1]) #리턴값에 인덱스를 부여하면 원하는 값만 출력 가능

Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


In [41]:
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
