## _Linear Regression_  
선형 회귀를 파이토치로 구현

In [1]:
import torch
import numpy as np
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [49]:
torch.manual_seed(1) #다음에 다시 실행해도 똑같은 결과가 나오게 하기 위함

In [19]:
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor(([2],[4],[6]))

In [4]:
print(x_train)
print(x_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


In [5]:
print(y_train)
print(y_train.shape)

tensor([[2.],
        [4.],
        [6.]])
torch.Size([3, 1])


In [6]:
#선형 회귀의 목표 - 가장 잘 맞는 W(가중치)와 b(편향,bias)를 찾는 것

In [20]:
W = torch.zeros(1,requires_grad=True) # 가중치 0으로 초기화, 학습을 통해 값이 변경됨을 명시

In [8]:
print(W)

tensor([0.], requires_grad=True)


In [21]:
b = torch.zeros(1, requires_grad=True)
print(b)

tensor([0.], requires_grad=True)


In [10]:
hypothesis = x_train * W + b #가설 선언
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [11]:
cost = torch.mean((hypothesis - y_train)**2) # 평균제곱오차(mse) 선언
print(cost)

tensor(18.6667, grad_fn=<MeanBackward0>)


In [22]:
#경사 하강법(gradient Descent)구현
optimizer = optim.SGD([W,b],lr=0.01) #SGD는 경사하강법의 일종, Lr는 학습률(learning rate)

In [13]:
optimizer.zero_grad() # grad를 0으로 초기화
cost.backward() # 비용함수(cost) 미분하여 grad 계산
optimizer.step() # W와 b를 업데이트

In [26]:
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor(([2],[4],[6]))

W = torch.zeros(1, requires_grad =True)
b = torch.zeros(1, requires_grad =True)

optimizer = optim.SGD([W,b],lr=0.01)

nb_epochs = 2000 # 반복 횟수
for epoch in range(nb_epochs + 1):
    hypothesis = x_train * W + b #가설 선언
    cost = torch.mean((hypothesis - y_train)**2) # 평균제곱오차(mse) 선언
    optimizer.zero_grad() # grad를 0으로 초기화
    cost.backward() # 비용함수(cost) 미분하여 grad 계산
    optimizer.step() # W와 b를 업데이트
    
    if epoch % 100 ==0:
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(epoch,nb_epochs,W.item(),b.item(),cost.item()))

Epoch    0/2000 W: 0.187, b: 0.080 Cost: 18.666666
Epoch  100/2000 W: 1.746, b: 0.578 Cost: 0.048171
Epoch  200/2000 W: 1.800, b: 0.454 Cost: 0.029767
Epoch  300/2000 W: 1.843, b: 0.357 Cost: 0.018394
Epoch  400/2000 W: 1.876, b: 0.281 Cost: 0.011366
Epoch  500/2000 W: 1.903, b: 0.221 Cost: 0.007024
Epoch  600/2000 W: 1.924, b: 0.174 Cost: 0.004340
Epoch  700/2000 W: 1.940, b: 0.136 Cost: 0.002682
Epoch  800/2000 W: 1.953, b: 0.107 Cost: 0.001657
Epoch  900/2000 W: 1.963, b: 0.084 Cost: 0.001024
Epoch 1000/2000 W: 1.971, b: 0.066 Cost: 0.000633
Epoch 1100/2000 W: 1.977, b: 0.052 Cost: 0.000391
Epoch 1200/2000 W: 1.982, b: 0.041 Cost: 0.000242
Epoch 1300/2000 W: 1.986, b: 0.032 Cost: 0.000149
Epoch 1400/2000 W: 1.989, b: 0.025 Cost: 0.000092
Epoch 1500/2000 W: 1.991, b: 0.020 Cost: 0.000057
Epoch 1600/2000 W: 1.993, b: 0.016 Cost: 0.000035
Epoch 1700/2000 W: 1.995, b: 0.012 Cost: 0.000022
Epoch 1800/2000 W: 1.996, b: 0.010 Cost: 0.000013
Epoch 1900/2000 W: 1.997, b: 0.008 Cost: 0.000008

In [27]:
#epoch는 전체 훈련 데이터가 학습에 한번 활용된 주기를 말한다. 위 코드는 2000번 수행하였다.
#결과를 보면 최적의 기울기 W는 2에 가깝고 b는 0에 가까운 것을 볼 수 있다.

In [28]:
#왜 grad를 zero로 초기화?
w = torch.tensor(2.0, requires_grad=True)
nb_epochs = 20
for epochs in range(nb_epochs+1):
    z = 2*w
    
    z.backward()
    print('수식을 w로 미분한 값: {}'.format(w.grad))

수식을 w로 미분한 값: 2.0
수식을 w로 미분한 값: 4.0
수식을 w로 미분한 값: 6.0
수식을 w로 미분한 값: 8.0
수식을 w로 미분한 값: 10.0
수식을 w로 미분한 값: 12.0
수식을 w로 미분한 값: 14.0
수식을 w로 미분한 값: 16.0
수식을 w로 미분한 값: 18.0
수식을 w로 미분한 값: 20.0
수식을 w로 미분한 값: 22.0
수식을 w로 미분한 값: 24.0
수식을 w로 미분한 값: 26.0
수식을 w로 미분한 값: 28.0
수식을 w로 미분한 값: 30.0
수식을 w로 미분한 값: 32.0
수식을 w로 미분한 값: 34.0
수식을 w로 미분한 값: 36.0
수식을 w로 미분한 값: 38.0
수식을 w로 미분한 값: 40.0
수식을 w로 미분한 값: 42.0


In [29]:
#위와 같이 미분값 2가 계속해서 누적되는 것을 알 수 있다. 따라서 미분값을 계속 0으로 초기화시켜 주어야 한다.

## _Auto Grad(자동 미분)_  
pytorch에서 지원하는 자동 미분 기능

In [30]:
import torch

In [44]:
w = torch.tensor(2.0, requires_grad=True)

In [45]:
y = w**2
z = 2*y + 5

In [46]:
z.backward() #w에 대한 미분(기울기) 계산

In [47]:
print('w로 미분한 값: {}'.format(w.grad))

w로 미분한 값: 8.0


## _Multivariable Linear regression_  
다중 선형 회귀

In [48]:
#다중 선형 회귀에서는 독립 변수 x가 여러 개임. 

In [50]:
x1_train = torch.FloatTensor([[73], [93], [89], [96], [73]])
x2_train = torch.FloatTensor([[80], [88], [91], [98], [66]])
x3_train = torch.FloatTensor([[75], [93], [90], [100], [70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [51]:
w1 = torch.zeros(1, requires_grad=True)
w2 = torch.zeros(1, requires_grad=True)
w3 = torch.zeros(1, requires_grad=True)
b = torch.zeros(1,requires_grad=True)

In [53]:
optimizer = optim.SGD([w1,w2,w3,b],lr=1e-5)
nb_epochs=1000
for epoch in range(nb_epochs+1):
    hypothesis = x1_train * w1 + x2_train * w2 + x3_train * w3 + b
    cost = torch.mean((hypothesis- y_train)**2)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 100 == 0:
        print('Epoch : {:4d}/{} w1 : {:.3f} w2 : {:.3f} w3 : {:.3f} b: {:.3f} Cost: {:.6f}'.format(epoch,nb_epochs,w1.item(),w2.item(),w3.item(),b.item(),cost.item()))

Epoch :    0/1000 w1 : 0.294 w2 : 0.294 w3 : 0.297 b: 0.003 Cost: 29661.800781
Epoch :  100/1000 w1 : 0.674 w2 : 0.661 w3 : 0.676 b: 0.008 Cost: 1.563634
Epoch :  200/1000 w1 : 0.679 w2 : 0.655 w3 : 0.677 b: 0.008 Cost: 1.497607
Epoch :  300/1000 w1 : 0.684 w2 : 0.649 w3 : 0.677 b: 0.008 Cost: 1.435026
Epoch :  400/1000 w1 : 0.689 w2 : 0.643 w3 : 0.678 b: 0.008 Cost: 1.375730
Epoch :  500/1000 w1 : 0.694 w2 : 0.638 w3 : 0.678 b: 0.009 Cost: 1.319511
Epoch :  600/1000 w1 : 0.699 w2 : 0.633 w3 : 0.679 b: 0.009 Cost: 1.266222
Epoch :  700/1000 w1 : 0.704 w2 : 0.627 w3 : 0.679 b: 0.009 Cost: 1.215696
Epoch :  800/1000 w1 : 0.709 w2 : 0.622 w3 : 0.679 b: 0.009 Cost: 1.167818
Epoch :  900/1000 w1 : 0.713 w2 : 0.617 w3 : 0.680 b: 0.009 Cost: 1.122429
Epoch : 1000/1000 w1 : 0.718 w2 : 0.613 w3 : 0.680 b: 0.009 Cost: 1.079378


## _벡터와 행렬 연산으로 바꾸기_

In [54]:
#x의 개수가 많아진다면 일일히 선언하기 어려움. 즉 벡터의 내적(곱셈) 을 이용.

In [55]:
x_train = torch.FloatTensor([[73,  80,  75], 
                               [93,  88,  93], 
                               [89,  91,  80], 
                               [96,  98,  100],   
                               [73,  66,  70]])
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])
#x_train에 5x3 행렬 한번에 선언

In [56]:
print(x_train.shape)
print(y_train.shape)

torch.Size([5, 3])
torch.Size([5, 1])


In [57]:
#가중치 W, 편향 b 선언
W = torch.zeros((3,1),requires_grad=True) #가중치의 크기를 벡터로 선언
b = torch.zeros(1,requires_grad=True)

In [58]:
hypothesis = x_train.matmul(W)+b

In [59]:
optimizer = optim.SGD([W, b], lr=1e-5)
nb_epochs=20
for epoch in range(nb_epochs+1):
    hypothesis = x_train.matmul(W)+b
    cost = torch.mean((hypothesis - y_train)**2)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    print('Epoch {:4d}/{} hypothesis: {} Cost: {:.6f}'.format(
        epoch, nb_epochs, hypothesis.squeeze().detach(), cost.item()
    ))


Epoch    0/20 hypothesis: tensor([0., 0., 0., 0., 0.]) Cost: 29661.800781
Epoch    1/20 hypothesis: tensor([66.7178, 80.1701, 76.1025, 86.0194, 61.1565]) Cost: 9537.694336
Epoch    2/20 hypothesis: tensor([104.5421, 125.6208, 119.2478, 134.7861,  95.8280]) Cost: 3069.590820
Epoch    3/20 hypothesis: tensor([125.9858, 151.3882, 143.7087, 162.4333, 115.4844]) Cost: 990.670288
Epoch    4/20 hypothesis: tensor([138.1429, 165.9963, 157.5768, 178.1071, 126.6283]) Cost: 322.481873
Epoch    5/20 hypothesis: tensor([145.0350, 174.2780, 165.4395, 186.9928, 132.9461]) Cost: 107.717064
Epoch    6/20 hypothesis: tensor([148.9423, 178.9730, 169.8976, 192.0301, 136.5279]) Cost: 38.687496
Epoch    7/20 hypothesis: tensor([151.1574, 181.6346, 172.4254, 194.8856, 138.5585]) Cost: 16.499043
Epoch    8/20 hypothesis: tensor([152.4131, 183.1435, 173.8590, 196.5043, 139.7097]) Cost: 9.365656
Epoch    9/20 hypothesis: tensor([153.1250, 183.9988, 174.6723, 197.4217, 140.3625]) Cost: 7.071114
Epoch   10/20 hyp