## _View_  
원소의 개수를 유지하면서 텐서의 크기를 변경. numpy의 reshape와 비슷함.

In [2]:
import numpy as np

In [4]:
import torch

In [6]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t) #3차원 텐서

In [7]:
print(ft.shape)

torch.Size([2, 2, 3])


In [8]:
#3차원->2차원 변경
print(ft.view([-1,3])) #-1은 첫번째 차원은 pytorch에 맡긴다는 의미. 2번째 차원의 크기는 3으로 변경
print(ft.view([-1,3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [9]:
#차원은 유지하고 크기(shape)만 변경
print(ft.view([-1,1,3]))
print(ft.view([-1,1,3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


## _squeeze_  
1인 차원이 있다면 제거한다.

In [10]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [11]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


## _unsqueeze_  
특정 위치에 1인 차원을 추가한다.

In [13]:
ft = torch.Tensor([0,1,2])
print(ft.shape)

torch.Size([3])


In [14]:
print(ft.unsqueeze(0)) #인덱스가 0부터 시작하므로 첫번째 차원에 추가한다.
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [15]:
#view 이용하여 같은 결과
print(ft.view(1,-1))
print(ft.view(1,-1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [16]:
print(ft.unsqueeze(1)) 
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [17]:
print(ft.unsqueeze(-1))  #-1은 마지막 차원을 의미
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


## _Type Casting_  
텐서의 자료형을 바꾸는 것.

In [18]:
lt = torch.LongTensor([1,2,3,4]) #long 자료형
print(lt)

tensor([1, 2, 3, 4])


In [19]:
print(lt.float()) #float으로 타입이 변경됨

tensor([1., 2., 3., 4.])


In [20]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [21]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


## _concatenate_
두 텐서 연결

In [22]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

In [23]:
print(torch.cat([x, y], dim=0)) #인자로 어느 차원을 늘릴 것인지 정할 수 있음. 이 경우에는 1차원

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [24]:
print(torch.cat([x, y], dim=1))

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


## _Stacking_  
벡터를 쌓는다

In [25]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [27]:
print(torch.stack([x,y,z]))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [31]:
print(torch.stack([x,y,z],dim=1))

tensor([[1., 2., 3.],
        [4., 5., 6.]])


## _ones_like & zeros_like_  
0으로만 이루어진 벡터와 1로만 이루어진 벡터

In [32]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [33]:
print(torch.ones_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [34]:
print(torch.zeros_like(x))

tensor([[0., 0., 0.],
        [0., 0., 0.]])


## _In-place Operation_  
덮어쓰기 연산

In [35]:
x = torch.FloatTensor([[1, 2], [3, 4]])

In [36]:
print(x.mul(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])


In [37]:
print(x.mul_(2.)) # 언더바를 붙이면 기존의 값을 덮어쓰기함.
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
